{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "13b610fe-2f8d-441d-aa16-38bec65cb131",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: mediapipe in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (0.10.11)\n",
      "Requirement already satisfied: opencv-python in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (4.11.0.86)\n",
      "Requirement already satisfied: absl-py in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (2.1.0)\n",
      "Requirement already satisfied: attrs>=19.1.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (24.2.0)\n",
      "Requirement already satisfied: flatbuffers>=2.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (25.1.24)\n",
      "Requirement already satisfied: jax in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (0.4.13)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (3.7.5)\n",
      "Requirement already satisfied: numpy in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (1.24.4)\n",
      "Requirement already satisfied: opencv-contrib-python in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (4.11.0.86)\n",
      "Requirement already satisfied: protobuf<4,>=3.11 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (3.20.3)\n",
      "Requirement already satisfied: sounddevice>=0.4.4 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from mediapipe) (0.5.1)\n",
      "Requirement already satisfied: CFFI>=1.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from sounddevice>=0.4.4->mediapipe) (1.17.1)\n",
      "Requirement already satisfied: ml-dtypes>=0.1.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from jax->mediapipe) (0.2.0)\n",
      "Requirement already satisfied: opt-einsum in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from jax->mediapipe) (3.4.0)\n",
      "Requirement already satisfied: scipy>=1.7 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from jax->mediapipe) (1.10.1)\n",
      "Requirement already satisfied: importlib-metadata>=4.6 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from jax->mediapipe) (7.0.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (1.1.1)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (4.55.8)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (1.4.7)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (24.1)\n",
      "Requirement already satisfied: pillow>=6.2.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (10.4.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (3.1.4)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (2.9.0.post0)\n",
      "Requirement already satisfied: importlib-resources>=3.2.0 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from matplotlib->mediapipe) (6.4.0)\n",
      "Requirement already satisfied: pycparser in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.21)\n",
      "Requirement already satisfied: zipp>=0.5 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from importlib-metadata>=4.6->jax->mediapipe) (3.20.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install mediapipe opencv-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a3f56a7f-58a0-4acc-b9b9-b6603769a80b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (2.0.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from pandas) (2025.1)\n",
      "Requirement already satisfied: numpy>=1.20.3 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from pandas) (1.24.4)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\user\\anaconda3\\envs\\finalwork\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "682e10b2-6097-4915-903d-7e0f4652fa14",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import mediapipe as mp\n",
    "import numpy as np\n",
    "import time\n",
    "import os\n",
    "import json\n",
    "from datetime import datetime\n",
    "import pandas as pd\n",
    "import logging\n",
    "\n",
    "class PostureDetectionSystem:\n",
    "    def __init__(self):\n",
    "        # Initialize MediaPipe Pose\n",
    "        self.mp_pose = mp.solutions.pose\n",
    "        self.mp_drawing = mp.solutions.drawing_utils\n",
    "        self.pose = self.mp_pose.Pose(\n",
    "            static_image_mode=False,\n",
    "            min_detection_confidence=0.7,\n",
    "            min_tracking_confidence=0.7\n",
    "        )\n",
    "\n",
    "        # Configuration parameters\n",
    "        self.config = {\n",
    "            'calibration_frames': 30,\n",
    "            'alert_cooldown': 5,\n",
    "            'shoulder_threshold_offset': 10,\n",
    "            'neck_threshold_offset': 10,\n",
    "            'poor_posture_threshold_time': 300,  # 5 minutes\n",
    "            'recording_interval': 3600  # 1 hour\n",
    "        }\n",
    "\n",
    "        # Initialize state variables\n",
    "        self.reset_state()\n",
    "        \n",
    "        # Setup logging\n",
    "        self.setup_logging()\n",
    "        \n",
    "        # Load previous calibration if exists\n",
    "        self.load_calibration()\n",
    "\n",
    "    def setup_logging(self):\n",
    "        logging.basicConfig(\n",
    "            filename='posture_detection.log',\n",
    "            level=logging.INFO,\n",
    "            format='%(asctime)s - %(levelname)s - %(message)s'\n",
    "        )\n",
    "        self.logger = logging.getLogger('PostureDetection')\n",
    "\n",
    "    def reset_state(self):\n",
    "        self.is_calibrated = False\n",
    "        self.calibration_frames = 0\n",
    "        self.calibration_data = {\n",
    "            'shoulder_angles': [],\n",
    "            'neck_angles': [],\n",
    "            'hip_angles': []\n",
    "        }\n",
    "        self.last_alert_time = 0\n",
    "        self.session_start_time = time.time()\n",
    "        self.poor_posture_start_time = None\n",
    "        self.posture_statistics = {\n",
    "            'good_posture_time': 0,\n",
    "            'poor_posture_time': 0,\n",
    "            'alert_count': 0\n",
    "        }\n",
    "\n",
    "    def calculate_angle(self, a, b, c):\n",
    "        \"\"\"Calculate angle between three points\"\"\"\n",
    "        ba = np.array([a[0] - b[0], a[1] - b[1]])\n",
    "        bc = np.array([c[0] - b[0], c[1] - b[1]])\n",
    "        cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))\n",
    "        angle = np.arccos(cosine_angle)\n",
    "        return np.degrees(angle)\n",
    "\n",
    "    def load_calibration(self):\n",
    "        \"\"\"Load calibration data from file\"\"\"\n",
    "        try:\n",
    "            with open('calibration_data.json', 'r') as f:\n",
    "                data = json.load(f)\n",
    "                self.shoulder_threshold = data['shoulder_threshold']\n",
    "                self.neck_threshold = data['neck_threshold']\n",
    "                self.hip_threshold = data['hip_threshold']\n",
    "                self.is_calibrated = True\n",
    "                self.logger.info(\"Loaded previous calibration data\")\n",
    "        except FileNotFoundError:\n",
    "            self.logger.info(\"No previous calibration data found\")\n",
    "\n",
    "    def process_frame(self, frame):\n",
    "        \"\"\"Process a single frame\"\"\"\n",
    "        rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "        results = self.pose.process(rgb_frame)\n",
    "        \n",
    "        if not results.pose_landmarks:\n",
    "            return frame, None\n",
    "\n",
    "        landmarks = results.pose_landmarks.landmark\n",
    "        frame_h, frame_w = frame.shape[:2]\n",
    "        \n",
    "        landmarks_dict = self.extract_landmarks(landmarks, frame_w, frame_h)\n",
    "        angles = self.calculate_angles(landmarks_dict)\n",
    "        \n",
    "        if not self.is_calibrated:\n",
    "            frame = self.handle_calibration(frame, angles)\n",
    "        else:\n",
    "            frame = self.analyze_posture(frame, angles)\n",
    "            \n",
    "        self.mp_drawing.draw_landmarks(\n",
    "            frame, \n",
    "            results.pose_landmarks, \n",
    "            self.mp_pose.POSE_CONNECTIONS,\n",
    "            self.mp_drawing.DrawingSpec(color=(0, 255, 0), thickness=2, circle_radius=2),\n",
    "            self.mp_drawing.DrawingSpec(color=(0, 0, 255), thickness=2)\n",
    "        )\n",
    "        \n",
    "        return frame, angles\n",
    "\n",
    "    def extract_landmarks(self, landmarks, frame_w, frame_h):\n",
    "        \"\"\"Extract and normalize landmark positions\"\"\"\n",
    "        return {\n",
    "            'left_shoulder': (\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.LEFT_SHOULDER.value].x * frame_w),\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.LEFT_SHOULDER.value].y * frame_h)\n",
    "            ),\n",
    "            'right_shoulder': (\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.RIGHT_SHOULDER.value].x * frame_w),\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.RIGHT_SHOULDER.value].y * frame_h)\n",
    "            ),\n",
    "            'left_ear': (\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.LEFT_EAR.value].x * frame_w),\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.LEFT_EAR.value].y * frame_h)\n",
    "            ),\n",
    "            'right_ear': (\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.RIGHT_EAR.value].x * frame_w),\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.RIGHT_EAR.value].y * frame_h)\n",
    "            ),\n",
    "            'left_hip': (\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.LEFT_HIP.value].x * frame_w),\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.LEFT_HIP.value].y * frame_h)\n",
    "            ),\n",
    "            'right_hip': (\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.RIGHT_HIP.value].x * frame_w),\n",
    "                int(landmarks[self.mp_pose.PoseLandmark.RIGHT_HIP.value].y * frame_h)\n",
    "            )\n",
    "        }\n",
    "\n",
    "    def calculate_angles(self, landmarks):\n",
    "        return {\n",
    "            'shoulder_angle': self.calculate_angle(\n",
    "                landmarks['left_shoulder'], landmarks['right_shoulder'], (landmarks['right_shoulder'][0], 0)\n",
    "            ),\n",
    "            'neck_angle': self.calculate_angle(\n",
    "                landmarks['left_ear'], landmarks['left_shoulder'], (landmarks['left_shoulder'][0], 0)\n",
    "            ),\n",
    "            'hip_angle': self.calculate_angle(\n",
    "                landmarks['left_hip'], landmarks['left_shoulder'], (landmarks['left_shoulder'][0], 0)\n",
    "            )\n",
    "        }\n",
    "\n",
    "    def handle_calibration(self, frame, angles):\n",
    "        if self.calibration_frames < self.config['calibration_frames']:\n",
    "            self.calibration_data['shoulder_angles'].append(angles['shoulder_angle'])\n",
    "            self.calibration_data['neck_angles'].append(angles['neck_angle'])\n",
    "            self.calibration_data['hip_angles'].append(angles['hip_angle'])\n",
    "            self.calibration_frames += 1\n",
    "            cv2.putText(frame, f\"Calibrating... {self.calibration_frames}/{self.config['calibration_frames']}\", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 2, cv2.LINE_AA)\n",
    "        else:\n",
    "            self.complete_calibration()\n",
    "        return frame\n",
    "\n",
    "    def complete_calibration(self):\n",
    "        self.shoulder_threshold = np.mean(self.calibration_data['shoulder_angles']) - self.config['shoulder_threshold_offset']\n",
    "        self.neck_threshold = np.mean(self.calibration_data['neck_angles']) - self.config['neck_threshold_offset']\n",
    "        self.hip_threshold = np.mean(self.calibration_data['hip_angles']) - self.config['shoulder_threshold_offset']\n",
    "        self.is_calibrated = True\n",
    "        self.logger.info(f\"Calibration complete - Shoulder: {self.shoulder_threshold:.1f}, Neck: {self.neck_threshold:.1f}, Hip: {self.hip_threshold:.1f}\")\n",
    "\n",
    "    def analyze_posture(self, frame, angles):\n",
    "        current_time = time.time()\n",
    "        poor_posture = (\n",
    "            angles['shoulder_angle'] < self.shoulder_threshold or\n",
    "            angles['neck_angle'] < self.neck_threshold or\n",
    "            angles['hip_angle'] < self.hip_threshold\n",
    "        )\n",
    "        \n",
    "        if poor_posture:\n",
    "            status = \"Bad Posture\"\n",
    "            color = (0, 0, 255)  # Red\n",
    "            if self.poor_posture_start_time is None:\n",
    "                self.poor_posture_start_time = current_time\n",
    "            poor_posture_duration = current_time - self.poor_posture_start_time\n",
    "            self.posture_statistics['poor_posture_time'] += time.time() - self.last_alert_time\n",
    "            if current_time - self.last_alert_time > self.config['alert_cooldown']:\n",
    "                self.handle_poor_posture_alert(poor_posture_duration)\n",
    "                self.last_alert_time = current_time\n",
    "                self.posture_statistics['alert_count'] += 1\n",
    "        else:\n",
    "            status = \"Good Posture\"\n",
    "            color = (0, 255, 0)  # Green\n",
    "            self.poor_posture_start_time = None\n",
    "            self.posture_statistics['good_posture_time'] += time.time() - self.last_alert_time\n",
    "        \n",
    "        self.draw_feedback(frame, status, color, angles)\n",
    "        return frame\n",
    "\n",
    "    def handle_poor_posture_alert(self, duration):\n",
    "        if duration > self.config['poor_posture_threshold_time']:\n",
    "            message = \"Warning: Poor posture for over 5 minutes! Please take a break and stretch.\"\n",
    "        else:\n",
    "            message = \"Poor posture detected! Please adjust your position.\"\n",
    "        self.logger.warning(message)\n",
    "\n",
    "    def draw_feedback(self, frame, status, color, angles):\n",
    "        cv2.putText(frame, status, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, color, 2, cv2.LINE_AA)\n",
    "        cv2.putText(frame, f\"Shoulder Angle: {angles['shoulder_angle']:.1f}\", (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 1, cv2.LINE_AA)\n",
    "        cv2.putText(frame, f\"Neck Angle: {angles['neck_angle']:.1f}\", (10, 90), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 1, cv2.LINE_AA)\n",
    "        cv2.putText(frame, f\"Hip Angle: {angles['hip_angle']:.1f}\", (10, 120), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 1, cv2.LINE_AA)\n",
    "\n",
    "def main():\n",
    "    system = PostureDetectionSystem()\n",
    "    cap = cv2.VideoCapture(0)\n",
    "    \n",
    "    while cap.isOpened():\n",
    "        ret, frame = cap.read()\n",
    "        if not ret:\n",
    "            continue\n",
    "\n",
    "        processed_frame, angles = system.process_frame(frame)\n",
    "        cv2.imshow('Posture Detection System', processed_frame)\n",
    "\n",
    "        if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "            break\n",
    "\n",
    "    cap.release()\n",
    "    cv2.destroyAllWindows()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n",
    "#########################the final one ################################################################################\n",
    "############################the final result###############################################################################"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0a3122f-5a6f-40cb-b0f3-fd8f7603c96e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
